config/routes.rb
Rails.application.routes.draw do
	resources :members, :except => [:show, :edit]

	resources :guilds, :except => [:index]

	devise_for :users
	resources :quests do
		member do
			put :finish
		end
	end	
	resources :unfinished
	resources :finished
	resources :users

	root 'quests#index'

end

app/models/quest.rb
class Quest < ActiveRecord::Base
    belongs_to :user
    validates_presence_of :name, :difficulty, :deadline
    validates_length_of :name, :minimum => 3
    #znajdowanie Questow ktore powinny byc przeniesione do nieukonczonych
	def self.current
		Quest.where("state LIKE ? AND deadline >= ? ", "current", Date.today)
	end
	def self.unfinished
		Quest.where("state LIKE ? AND deadline <= ?", "unfinished", Date.today)
	end
	def self.finished
		Quest.where("state LIKE ? ", "finished")
	end
	def self.failed
		Quest.where("state LIKE ? AND deadline <= ?", "current", Date.today)
	end
	def self.unsynced
		Quest.where("state LIKE ? AND deadline < ?", "current", Date.today)
	end
end

app/controllers/quests_controller.rb
class QuestsController < ApplicationController
	before_action :authenticate_user!
	before_action :current_quests, only: [:index, :create]
	respond_to :html, :js
	before_action :set_quest, only: [:finish, :show, :edit, :update, :destroy]
	before_action :sync, only: [:index]
	before_action :exp_values, only: [:finish]
	# GET /quests
	# GET /quests.json

	# GET /quests/1
	# GET /quests/1.json
	def show
	end

	# GET /quests/new
	def new
		@quest = current_user.quests.new
	end

	# GET /quests/1/edit
	def edit
	end


	# POST /quests
	# POST /quests.json
	def create
		@quest = current_user.quests.new(quest_params)
		respond_to do |format|
			if @quest.save
				format.html { redirect_to @quest, notice: 'Quest was successfully created.' }
				format.json { render :show, status: :created, location: @quest }
			else
				format.html { render :new }
				format.json { render json: @quest.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /quests/1
	# PATCH/PUT /quests/1.json
	def update
		respond_to do |format|
			if @quest.update(quest_params)
				format.html { redirect_to @quest, notice: 'Quest was successfully updated.' }
				format.json { render :show, status: :ok, location: @quest }
			else
				format.html { render :edit }
				format.json { render json: @quest.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /quests/1
	# DELETE /quests/1.json
	def destroy
		@quest.destroy	
		respond_to do |format|
			format.html { redirect_to quests_url, notice: 'Quest was cancelled.' }
			format.json { head :no_content }
		end
	end
	def sync
		@quest= current_user.quests.unsynced
		@quest.update_all("state = 'unfinished'")
	end
	def finish
		if @quest.update_attribute(:state, 'finished')
			if @quest.difficulty=='easy'
				@exp_value=@easy
			end
			if @quest.difficulty=='normal'
				@exp_value=@normal
			end
			if @quest.difficulty=='epic'
				@exp_value=@epic
			end
			if @quest.difficulty=='legendary'
				@exp_value=@legendary
			end
			
			current_user.increment!(:experience, @exp_value)


			respond_to do |format|
				format.html { redirect_to quests_url, notice: "Congratulations on finishing your quest" }
				format.json { head :no_content }
			end
		end
	end

	private
	def current_quests
		@quests = current_user.quests.current
	end
	def exp_values
		@easy=10
		@normal=50
		@epic=100
		@legendary=300
	end
	# Use callbacks to share common setup or constraints between actions.
	def set_quest
		@quest = Quest.find(params[:id])
	end
	# Never trust parameters from the scary internet, only allow the white list through.
	def quest_params
		params.require(:quest).permit(:name, :description, :difficulty, :deadline, :state)
	end

end

app/helpers/quests_helper.rb
module QuestsHelper
end

app/views/quests/_form.html.erb
<%= form_for(@quest) do |f| %>
  <% if @quest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quest.errors.count, "error") %> prohibited this quest from being saved:</h2>

      <ul>
      <% @quest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% my_date = Time.now + 6.days %>

  <div class="actions">
      <%= f.text_field :name %></br>  
      <%= f.text_area :description %></br>
      <%= f.radio_button :difficulty , 'legendary' %>
      <%= f.label :difficulty, 'Legendary', :value => 'legendary' %></br>
      <%= f.radio_button :difficulty , 'epic' %>
      <%= f.label :difficulty, 'Epic', :value => 'epic' %></br>
      <%= f.radio_button :difficulty , 'hard' %>
      <%= f.label :difficulty, 'Hard', :value => 'hard' %></br>
      <%= f.radio_button :difficulty , 'normal', :checked => true%>
      <%= f.label :difficulty, 'Normal', :value => 'normal' %></br>
      <%= f.radio_button :difficulty , 'easy' %>
      <%= f.label :difficulty, 'Easy', :value => 'easy' %></br>
      <%= f.date_select :deadline %>
    <%= f.submit %>
<% end %>

app/views/quests/create.js.erb
$('#quest-table').html("<%= j (render @tasks) %>");
$('#quest-form').slideUp(350);

app/views/quests/edit.html.erb
<h1>Editing Quest</h1>

<%= render 'form' %>

<%= link_to 'Show', @quest %> |
<%= link_to 'Back', quests_path %>

app/views/quests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Active Quests</h1>

<div class="row">
	<div class="col-xs-6">
		<div class="table">
			<table class="table table-hover" >
				<thead>
					<tr>
						<th colspan="1">Title</th>
						<th colspan="1">Difficulty</th>
						<th colspan="1">Deadline</th>
						<th colspan="4">Actons</th>
						<th colspan="1" style="text-align:right">
						<%=link_to new_quest_path do%>
							<span class="glyphicon glyphicon-plus"></span>
						<%end%>
						</th>
					</tr>
				</thead>

				<tbody class="align-right">
					<% @quests.each do |quest| %>
						<tr >
							<td><%= quest.name %> </td>
							<td><%= quest.difficulty %> </td>
							<td><%= quest.deadline %> </td>
							<td><div><%= link_to  finish_quest_path(quest), :method => :put, class: "btn btn-default" do%>
									<span class="glyphicon glyphicon-ok"></span>
								<% end %>	
								<%= link_to quest, class: "btn btn-default" do %>
									<span class="glyphicon glyphicon-folder-open"></span>
								<%end%>

								<%= link_to edit_quest_path(quest), class: "btn btn-default" do %>
									<span class="glyphicon glyphicon-cog"></span>
								<% end %>
								<%= link_to quest, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" do %>
									<span class="glyphicon glyphicon-trash"></span>
								<%end%>
								</div>
							</td>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
	<div class="col-xs-2"></div>
	<div class="col-xs-4" style="border-left:solid 1px black">
		<%= render "users/show" %>
	</div>
</div>

<br>

app/views/quests/new.html.erb
<h1>New Quest</h1>

<%= render 'form' %>

<%= link_to 'Back', quests_path %>

app/views/quests/new.js.erb
$('#quest-form').html("<%= escape_javascript (render 'form') %>");
$('#quest-form').slideDown(366);

app/views/quests/show.html.erb
<p id="notice"><%= notice %></p>

<%= @quest.name %></br>
<%= @quest.description %></br>
<%= @quest.difficulty %></br>
<%= @quest.deadline %></br>
<%= @quest.state %></br>