config/routes.rb
Rails.application.routes.draw do
	resources :members, :except => [:show, :edit]

	resources :guilds, :except => [:index]

	devise_for :users
	resources :quests do
		member do
			put :finish
		end
	end	
	resources :unfinished
	resources :finished
	resources :users

	root 'quests#index'

end

app/models/guild.rb
class Guild < ActiveRecord::Base
	has_many :members
	has_many :users, through: :members 
    	validates_presence_of :name
    	validates_length_of :name, :minimum => 4
end

app/controllers/guilds_controller.rb
class GuildsController < ApplicationController
	before_action :authenticate_user!
	before_action :set_guild, only: [:show, :edit, :update, :destroy]
	#	after_action :set_leader_group_id, only: [:create]

	# GET /guilds
	# GET /guilds.json

	# GET /guilds/1
	# GET /guilds/1.json
	def show
	end

	# GET /guilds/new
	def new
		if current_user.members.nil?
			@guild = Guild.new
		else
			redirect_to members_url, notice: 'You already belong to group' 
		end
	end

	# GET /guilds/1/edit
	def edit
	end

	# POST /guilds
	# POST /guilds.json
	def create
		if current_user.members.nil?
		@guild = Guild.new(guild_params)
		respond_to do |format|
			if @guild.save
				@member = Member.new(guild_id: @guild.id, user_id: current_user.id, leader: true)
				@member.save
				format.html { redirect_to quests_path, notice: 'Guild was successfully created.' }
				format.json { render :show, status: :created, location: @guild }
			else
				format.html { render :new }
				format.json { render json: @guild.errors, status: :unprocessable_entity }
			end
		end
		end
	end

	# PATCH/PUT /guilds/1
	# PATCH/PUT /guilds/1.json
	def update
		respond_to do |format|
			if @guild.update(guild_params)
				format.html { redirect_to @guild, notice: 'Guild was successfully updated.' }
				format.json { render :show, status: :ok, location: @guild }
			else
				format.html { render :edit }
				format.json { render json: @guild.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /guilds/1
	# DELETE /guilds/1.json
	def destroy
		@guild.destroy
		respond_to do |format|
			format.html { redirect_to guilds_url, notice: 'Guild was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	private
	# Use callbacks to share common setup or constraints between actions.
	def set_guild
		@guild = Guild.find(params[:id])
	end
	# Never trust parameters from the scary internet, only allow the white list through.
	def guild_params
		params.require(:guild).permit(:name, :motto)
	end
end

app/helpers/guilds_helper.rb
module GuildsHelper
end

app/views/guilds/_form.html.erb
<%= form_for(@guild) do |f| %>
  <% if @guild.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@guild.errors.count, "error") %> prohibited this guild from being saved:</h2>

      <ul>
      <% @guild.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :motto %><br>
    <%= f.text_area :motto %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/guilds/edit.html.erb
<h1>Editing Guild</h1>

<%= render 'form' %>

<%= link_to 'Show', @guild %> |
<%= link_to 'Back', guilds_path %>

app/views/guilds/new.html.erb
<h1>New Guild</h1>

<%= render 'form' %>

<%= link_to 'Back', quests_path %>

app/views/guilds/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row"> 
	<div class="col-md-3" style="border-bottom: solid 1px black">
		<h1>Guild Menu</h1>
	</div>
</div>
<div class="row">
	<div class="col-md-6">
		<h4>
			<strong>
				<%= @guild.name %>
			</strong>
		</h4></br>
		<p>
		<strong>Motto:</strong>
		<%= @guild.motto %>
		</p>
		</br>
	</div>
	<div class="col-md-2">
	</div>
	<div class="col-md-4">
		<%= render "guild_members" %>
	</div>
</div>
<%= link_to 'Edit', edit_guild_path(@guild) %> |
<%= link_to 'Back', quests_path %>