config/routes.rb
Rails.application.routes.draw do
	resources :members, :except => [:show, :edit]

	resources :guilds, :except => [:index]

	devise_for :users
	resources :quests do
		member do
			put :finish
		end
	end	
	resources :unfinished
	resources :finished
	resources :users

	root 'quests#index'

end

app/views/layouts/_carousel.html.erb
<div id="myCarousel" class="carousel slide">
	   <ol class="carousel-indicators">
	    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
	    <li data-target="#myCarousel" data-slide-to="1"></li>
	    <li data-target="#myCarousel" data-slide-to="2"></li>
	    <li data-target="#myCarousel" data-slide-to="3"></li>
	  </ol>
  <div class="carousel-inner">
    <div class="item active">
	    <%= image_tag '1.jpg' %>
      <div class="container">
        <div class="carousel-caption">
          <h1>Find Your Destination</h1>
        </div>
      </div>
    </div>
    <div class="item">
	    <%= image_tag '2.jpg' %>
    </div>
    <div class="item">
	    <%= image_tag '1.jpg' %>
    </div>
    <div class="item">
	    <%= image_tag '2.jpg' %>
    </div>
  </div>
</div><!-- /.carousel -->

app/views/layouts/_footer.html.erb
<div id="myfooter" class="row">
	<div class="col-xs-12"> Footer </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<%= link_to 'EpicQuestJourney', quests_path, class: "navbar-brand" %>
		</div>

		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<% if user_signed_in? %>
				<ul class="nav navbar-nav navbar-left">
					<li class="dropdown">
						<a class="dropdown-toggle" aria-expanded="false" role="button" data-toggle="dropdown" href="#">Quests<span class="caret"></span></a>
						<ul class="dropdown-menu" role="menu">
							<li>
								<%= link_to "Active", quests_path %>
							</li>	
							<li>
								<%= link_to "Finished", finished_index_path %>
							</li>	
							<li>
								<%= link_to "Failed", unfinished_index_path %>
							</li>	
							<li class="divider"></li> 
							<li>
								<%= link_to "New Quest", new_quest_path %>
							</li>

						</ul>

					</li>
				</ul>
			<% end %>
			<ul class="nav navbar-nav navbar-right">
				<% if user_signed_in? %>
					<li>
						<%=link_to new_quest_path do%>
							<span class="glyphicon glyphicon-plus"></span>
						<%end%>
					</li>
					<li class="dropdown">
						<a class="dropdown-toggle" aria-expanded="false" role="button" data-toggle="dropdown" href="#"><span class="glyphicon glyphicon-user"></span></a>
						<ul class="dropdown-menu" role="menu">
							<li style="text-align:center">
								<div><span class="glyphicon glyphicon-user" style="font-size: 2em"></span><h4><%=link_to current_user.nickname, current_user %></h4></div>
							</li>
							<li>
								<%= link_to "Guild", guild_path(current_user.guilds.first.id) %>
							</li>
							<li class="divider"></li>
							<li>
								<%= link_to "Sign out", destroy_user_session_path, :method => :delete %></p>
							</li>
						</ul>

					</li>
				<% end %>
			</ul>
		</div>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EpicQuestJourney</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/navbar' %>
	<div id="main-container" class="container-fluid">

<%= yield %>

	</div>
</body>
</html>