config/routes.rb
Rails.application.routes.draw do
	resources :members, :except => [:show, :edit]

	resources :guilds, :except => [:index]

	devise_for :users
	resources :quests do
		member do
			put :finish
		end
	end	
	resources :unfinished
	resources :finished
	resources :users

	root 'quests#index'

end

app/models/member.rb
class Member < ActiveRecord::Base
	belongs_to :user
	belongs_to :guild
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
	before_action :authenticate_user!
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  # GET /members
  # GET /members.json
  def index
	  @user = current_user
	  @guild = @user.guilds.first

	  @members = @guild.users.all
  end

  # GET /members/1
  # GET /members/1.json

  # GET /members/new
  def new
	  if current_user.members.first.leader == true
    @member = Member.new
	  else
		redirect_to members_url, notice: 'You dont have rights to do it' 
	  end
  end
  # GET /members/1/edit

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)
	@member.guild_id = current_user.guilds.first.id
	@member.leader=false
    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
    # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:user_id)
    end
end

app/helpers/member_helper.rb
module MemberHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.erb
<%= form_for(@member) do |f| %>
	<% if @member.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

			<ul>
				<% @member.errors.full_messages.each do |message| %>
					<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<div class="form-group">
		
		User ID:<%= f.text_field :user_id, autofocus: true, class: "form-control" %>
	</div>


	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>

app/views/members/edit.html.erb
<h1>Editing Member</h1>

<%= render 'form' %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Members</h1>

<%= current_user.id %>
<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
	      <td><%= @guild.name%></td>
	      <td><%= member.nickname %></td>
	      <td><%= member.id %></td>
		<td><%= member.members.first.id %></td>

	<td><% if  current_user.members.first.leader == true || member.id==current_user.id %>
		<%= link_to 'Destroy', member.members.first, method: :delete, data: { confirm: 'Are you sure?' }%>
		<% end %>
	</td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user.members.first.leader == true %>
<%= link_to 'New Member', new_member_path %>
<% end %>

app/views/members/new.html.erb
<h1>New Member</h1>

<%= render 'form' %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>